-- Insert test tickets directly into the database
-- This script should be run in the Supabase SQL editor

-- First, let's get the first organization ID
-- (You'll need to replace this with an actual organization ID from your database)
INSERT INTO public.tickets (
  organization_id,
  ticket_number,
  title,
  description,
  type,
  category,
  subcategory,
  priority,
  urgency,
  impact,
  status,
  tags,
  custom_fields,
  created_at,
  updated_at
) VALUES 
(
  (SELECT id FROM public.organizations LIMIT 1),
  'BSM000001',
  'Inability to Save Changes in Profile Settings',
  'I''ve encountered an issue where changes made to profile settings are not being saved properly. This includes updating personal information, preferences, and notification settings. The changes appear to save initially but revert back to the original values after refreshing the page.',
  'incident',
  'Technical',
  'Profile Management',
  'medium',
  'medium',
  'medium',
  'new',
  ARRAY['profile', 'settings', 'bug'],
  '{"customer_reported_via": "email", "browser": "Chrome", "os": "Windows 10", "notes": "Customer reported via email"}'::jsonb,
  NOW(),
  NOW()
),
(
  (SELECT id FROM public.organizations LIMIT 1),
  'BSM000002',
  'Upcoming subscription renewal discussion',
  'Hi there, I wanted to discuss our upcoming subscription renewal. Can you help me review the renewal options and pricing? We''re considering upgrading to a higher tier plan and would like to understand the benefits and any available discounts.',
  'request',
  'Billing',
  'Subscription',
  'low',
  'low',
  'low',
  'new',
  ARRAY['billing', 'subscription', 'renewal'],
  '{"customer_contacted_via": "phone", "current_plan": "Basic", "interested_in": "Premium", "notes": "Customer contacted via phone"}'::jsonb,
  NOW(),
  NOW()
),
(
  (SELECT id FROM public.organizations LIMIT 1),
  'BSM000003',
  'Dark Mode for the Dashboard',
  'Customer suggested implementing a dark mode option for the dashboard interface. This would improve user experience during night hours and reduce eye strain. The feature should include a toggle switch and remember user preference across sessions.',
  'request',
  'Feature Request',
  'UI/UX',
  'medium',
  'low',
  'medium',
  'in_progress',
  ARRAY['dark-mode', 'ui', 'feature-request'],
  '{"customer_suggested_via": "feedback_form", "priority_level": "nice_to_have", "estimated_effort": "2-3 weeks", "notes": "Customer suggested on social media"}'::jsonb,
  NOW(),
  NOW()
),
(
  (SELECT id FROM public.organizations LIMIT 1),
  'BSM000004',
  'Cancellation of Zendesk Subscription',
  'Customer requested assistance with canceling their Zendesk subscription. They want to understand the cancellation process, any applicable fees, and how to export their data before the subscription ends.',
  'request',
  'Billing',
  'Cancellation',
  'urgent',
  'high',
  'high',
  'in_progress',
  ARRAY['cancellation', 'zendesk', 'billing'],
  '{"customer_requested_via": "email", "subscription_end_date": "2024-12-31", "data_export_required": true, "notes": "Customer requested via email"}'::jsonb,
  NOW(),
  NOW()
),
(
  (SELECT id FROM public.organizations LIMIT 1),
  'BSM000005',
  'Email Integration Not Working',
  'The email integration feature is not working properly. Emails are not being synced with the ticket system, and notifications are not being sent to customers. This is affecting our customer support workflow significantly.',
  'incident',
  'Technical',
  'Integration',
  'high',
  'high',
  'high',
  'open',
  ARRAY['email', 'integration', 'critical'],
  '{"affected_services": ["email_sync", "notifications"], "first_reported": "2024-01-15T10:30:00Z", "workaround_available": false, "notes": "Customer reported via support chat"}'::jsonb,
  NOW(),
  NOW()
),
(
  (SELECT id FROM public.organizations LIMIT 1),
  'BSM000006',
  'Password Reset Functionality',
  'Users are unable to reset their passwords using the forgot password feature. The reset emails are not being sent, and the reset links are not working properly. This is blocking user access to the system.',
  'incident',
  'Security',
  'Authentication',
  'critical',
  'critical',
  'critical',
  'open',
  ARRAY['password', 'security', 'authentication'],
  '{"security_impact": "high", "affected_users": "all", "immediate_action_required": true, "notes": "Customer reported via phone"}'::jsonb,
  NOW(),
  NOW()
);

